highlighter: rouge
permalink: ./:title
title: "Cheltenham Open Data"
description: "// collecting and disseminating localised open data"
author: "Mat"
url: https://cod.thechels.uk
copyright: "MB"
encoding: UTF-8
future: false
repository: Mat-0/cheltenham-open-data
defaultImagePath: "/images/splashscreens/apple-touch-icon-180x180.png"
github:
  repository_url: https://github.com/Mat-0/cheltenham-open-data
  branch: main
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
  - name: Farmers Market
    link: /farmers-market
  - name: Fix My Street
    link: /fix-my-street
  - name: Flood Warnings
    link: /flood-warnings
  - name: Food Bank
    link: /foodbank
  - name: Terrorism
    link: /terrorism
  - name: Street Crime
    link: /street-crime
  - name: News
    link: /news
  - name: Help
    link: /helpful
